In [1]:
# Display plots in the notebook
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [26]:
import pandas as pd
import numpy as np

In [11]:
lodes = pd.read_csv('../ny_od_main_JT00_2013.csv', dtype={'w_geocode': str, 'h_geocode': str})

In [16]:
lodes['w_county'] = lodes['w_geocode'].str[2:5]
lodes['h_county'] = lodes['h_geocode'].str[2:5]

In [17]:
lodes

,w_geocode,h_geocode,S000,SA01,SA02,SA03,SE01,SE02,SE03,SI01,SI02,SI03,createdate,w_county,h_county
0,360010001001004,360010004032010,1,0,1,0,0,0,1,0,1,0,20150727,001,001
1,360010001001004,360010020005001,1,0,1,0,0,0,1,0,1,0,20150727,001,001
2,360010001001004,360010144012034,1,0,1,0,0,0,1,0,1,0,20150727,001,001
3,360010001001004,360210005001006,1,0,1,0,0,0,1,0,1,0,20150727,001,021
4,360010001001004,360830411001025,1,0,1,0,0,0,1,0,1,0,20150727,001,083
5,360010001001004,360830520021025,1,0,1,0,0,0,1,0,1,0,20150727,001,083
6,360010001001004,360830522011029,1,0,1,0,0,0,1,0,1,0,20150727,001,083
7,360010001001004,360910617021018,1,0,1,0,0,0,1,0,1,0,20150727,001,091
8,360010001001004,360930329011016,1,0,1,0,0,0,1,0,1,0,20150727,001,093
9,360010001001004,361150840003004,1,0,1,0,0,0,1,0,1,0,20150727,001,115
10,360010001001004,361219705005002,1,0,0,1,0,0,1,0,1,0,20150727,001,121
11,360010001001005,360010001001018,1,0,1,0,0,0,1,1,0,0,20150727,001,001
12,360010001001005,360010003001049,1,1,0,0,0,1,0,1,0,0,20150727,001,001
13,360010001001005,360010003003005,1,1,0,0,0,1,0,1,0,0,20150727,001,001
14,360010001001005,360010003003009,1,0,1,0,0,0,1,1,0,0,20150727,001,001
15,360010001001005,360010016003004,1,1,0,0,1,0,0,1,0,0,20150727,001,001
16,360010001001005,360010020001001,1,1,0,0,0,1,0,1,0,0,20150727,001,001
17,360010001001005,360010127002024,1,0,0,1,0,1,0,0,1,0,20150727,001,001
18,360010001001005,360010131002003,1,1,0,0,0,1,0,1,0,0,20150727,001,001
19,360010001001005,360010131003026,1,0,1,0,0,0,1,1,0,0,20150727,001,001
20,360010001001005,360010135083010,1,0,0,1,0,0,1,1,0,0,20150727,001,001
21,360010001001005,360010136023020,1,0,1,0,0,0,1,1,0,0,20150727,001,001
22,360010001001005,360010138021006,1,1,0,0,0,0,1,1,0,0,20150727,001,001
23,360010001001005,360010138021007,1,0,0,1,0,1,0,0,1,0,20150727,001,001
24,360010001001005,360010139011001,1,1,0,0,0,1,0,1,0,0,20150727,001,001
25,360010001001005,360010145011107,1,0,0,1,0,0,1,0,1,0,20150727,001,001
26,360010001001005,360010146073021,1,0,1,0,0,0,1,1,0,0,20150727,001,001
27,360010001001005,360010148011009,1,0,0,1,0,1,0,1,0,0,20150727,001,001
28,360010001001005,360191007001041,1,0,1,0,0,1,0,1,0,0,20150727,001,019
29,360010001001005,360191013002016,1,0,1,0,0,1,0,1,0,0,20150727,001,019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6834127,361231505004019,361231501004034,1,0,1,0,0,1,0,0,0,1,20150727,123,123
6834128,361231505004019,361231501004060,1,1,0,0,0,1,0,0,0,1,20150727,123,123
6834129,361231505004019,361231503002106,1,0,1,0,0,1,0,0,0,1,20150727,123,123
6834130,361231505004019,361231504003018,1,0,1,0,0,1,0,0,0,1,20150727,123,123
6834131,361231505004019,361231505001008,1,0,1,0,1,0,0,0,0,1,20150727,123,123
6834132,361231505004019,361231505004006,1,0,1,0,0,1,0,0,0,1,20150727,123,123
6834133,361231505004020,360039508002017,1,1,0,0,0,1,0,0,1,0,20150727,123,003
6834134,361231505004020,360110403003068,1,0,1,0,0,0,1,0,1,0,20150727,123,011
6834135,361231505004020,360290155032014,1,0,0,1,0,0,1,0,1,0,20150727,123,029
6834136,361231505004020,360670160013001,1,0,1,0,1,0,0,0,1,0,20150727,123,067
6834137,361231505004020,360690508001009,1,0,1,0,0,1,0,0,1,0,20150727,123,069
6834138,361231505004020,360690515003007,1,0,1,0,1,0,0,0,1,0,20150727,123,069
6834139,361231505004020,360690521003033,1,0,0,1,0,1,0,0,1,0,20150727,123,069
6834140,361231505004020,360710152006078,1,0,1,0,0,0,1,0,1,0,20150727,123,071
6834141,361231505004020,360999501002056,1,0,0,1,0,1,0,0,1,0,20150727,123,099
6834142,361231505004020,361019602002099,1,0,1,0,0,1,0,0,1,0,20150727,123,101
6834143,361231505004020,361019614002017,1,0,0,1,1,0,0,0,1,0,20150727,123,101
6834144,361231505004020,361019614002056,1,0,1,0,0,1,0,0,1,0,20150727,123,101
6834145,361231505004020,361090022003044,1,0,1,0,1,0,0,0,1,0,20150727,123,109
6834146,361231505004020,361219701002032,1,1,0,0,0,0,1,0,1,0,20150727,123,121
6834147,361231505004020,361231501001075,1,0,1,0,0,1,0,0,1,0,20150727,123,123
6834148,361231505004020,361231501005090,1,0,0,1,0,1,0,0,1,0,20150727,123,123
6834149,361231505004020,361231502001025,1,0,1,0,0,0,1,0,1,0,20150727,123,123
6834150,361231505004020,361231502001067,1,1,0,0,1,0,0,0,1,0,20150727,123,123
6834151,361231505004020,361231502002096,1,1,0,0,0,1,0,0,1,0,20150727,123,123
6834152,361231505004020,361231503003101,1,1,0,0,0,1,0,0,1,0,20150727,123,123
6834153,361231505004020,361231504001020,1,0,0,1,1,0,0,0,1,0,20150727,123,123
6834154,361231505004020,361231504001041,1,0,1,0,0,1,0,0,1,0,20150727,123,123
6834155,361231505004020,361231505002038,1,0,0,1,0,1,0,0,1,0,20150727,123,123
6834156,361231505004020,361231505004022,1,0,0,1,1,0,0,0,1,0,20150727,123,123

In [19]:
counties = '005|047|061|081|085'

In [23]:
nyc_lodes = lodes[lodes['w_county'].str.contains(counties)&lodes['h_county'].str.contains(counties)]

In [24]:
nyc_lodes

,w_geocode,h_geocode,S000,SA01,SA02,SA03,SE01,SE02,SE03,SI01,SI02,SI03,createdate,w_county,h_county
203699,360050002001004,360050079003001,1,0,1,0,0,1,0,0,1,0,20150727,005,005
203700,360050002001004,360050123001000,1,0,1,0,0,0,1,0,1,0,20150727,005,005
203701,360050002001004,360050151002001,1,0,1,0,0,0,1,0,1,0,20150727,005,005
203702,360050002001004,360050399011001,1,0,1,0,1,0,0,0,1,0,20150727,005,005
203703,360050002001004,360050399023002,1,0,1,0,0,1,0,0,1,0,20150727,005,005
203705,360050002001004,360810415002001,1,0,0,1,0,1,0,0,1,0,20150727,005,081
203706,360050002001004,360810499002003,1,1,0,0,0,1,0,0,1,0,20150727,005,081
203710,360050002002002,360610257001004,1,0,1,0,1,0,0,0,0,1,20150727,005,061
203711,360050002002002,360810001001008,1,0,1,0,1,0,0,0,0,1,20150727,005,081
203712,360050002002003,360050002001000,1,0,1,0,0,0,1,1,0,0,20150727,005,005
203713,360050002002003,360810403001001,1,0,0,1,0,1,0,1,0,0,20150727,005,081
203714,360050002002008,360050216013000,1,0,0,1,0,1,0,0,0,1,20150727,005,005
203715,360050002002008,360050221012000,1,0,1,0,0,1,0,0,0,1,20150727,005,005
203716,360050002002008,360610223021000,1,0,0,1,0,0,1,0,0,1,20150727,005,061
203717,360050002002010,360050020001003,1,0,0,1,1,0,0,0,0,1,20150727,005,005
203718,360050002002010,360050237031002,1,0,1,0,1,0,0,0,0,1,20150727,005,005
203719,360050002003000,360050002002006,1,0,1,0,1,0,0,0,0,1,20150727,005,005
203720,360050002003000,360050002003000,1,0,1,0,1,0,0,0,0,1,20150727,005,005
203721,360050002003000,360050002003009,1,0,1,0,1,0,0,0,1,0,20150727,005,005
203722,360050002003000,360050004002003,1,0,1,0,0,1,0,0,0,1,20150727,005,005
203723,360050002003000,360050044002000,1,1,0,0,0,1,0,0,0,1,20150727,005,005
203724,360050002003000,360050044003002,1,0,1,0,0,1,0,0,0,1,20150727,005,005
203725,360050002003000,360050048002000,1,0,0,1,0,1,0,0,0,1,20150727,005,005
203726,360050002003000,360050079004001,1,0,1,0,0,1,0,0,1,0,20150727,005,005
203727,360050002003000,360050185001005,1,1,0,0,0,1,0,0,0,1,20150727,005,005
203728,360050002003000,360050227031001,1,0,1,0,0,1,0,0,1,0,20150727,005,005
203729,360050002003000,360610032006001,1,0,1,0,1,0,0,0,0,1,20150727,005,061
203730,360050002003000,360810500002004,1,0,1,0,1,0,0,0,0,1,20150727,005,081
203731,360050002003000,360811377002003,1,1,0,0,0,1,0,0,0,1,20150727,005,081
203733,360050002003011,360050002001002,1,0,1,0,0,1,0,0,1,0,20150727,005,005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5450690,360850323001021,360850011001000,1,0,1,0,0,1,0,1,0,0,20150727,085,085
5450691,360850323001021,360850112021006,1,0,1,0,0,1,0,0,1,0,20150727,085,085
5450692,360850323001021,360850147002005,1,0,0,1,0,1,0,0,1,0,20150727,085,085
5450693,360850323001021,360850170103000,1,0,1,0,0,0,1,1,0,0,20150727,085,085
5450694,360850323001021,360850176004010,1,0,1,0,1,0,0,1,0,0,20150727,085,085
5450695,360850323001021,360850177004009,1,0,0,1,0,0,1,1,0,0,20150727,085,085
5450696,360850323001021,360850207001005,1,0,1,0,1,0,0,1,0,0,20150727,085,085
5450697,360850323001021,360850207002000,1,0,1,0,1,0,0,1,0,0,20150727,085,085
5450698,360850323001021,360850207003005,1,0,1,0,1,0,0,1,0,0,20150727,085,085
5450699,360850323001021,360850207004009,1,0,1,0,1,0,0,1,0,0,20150727,085,085
5450700,360850323001021,360850208043015,1,0,0,1,0,0,1,1,0,0,20150727,085,085
5450701,360850323001021,360850226003002,1,0,1,0,0,1,0,0,1,0,20150727,085,085
5450702,360850323001021,360850231001012,1,1,0,0,0,1,0,0,1,0,20150727,085,085
5450703,360850323001021,360850244011001,1,0,0,1,0,0,1,0,1,0,20150727,085,085
5450704,360850323001021,360850273012002,1,0,0,1,0,0,1,1,0,0,20150727,085,085
5450705,360850323001021,360850277051005,1,0,1,0,0,1,0,0,1,0,20150727,085,085
5450706,360850323001021,360850303023003,1,0,0,1,0,1,0,0,1,0,20150727,085,085
5450708,360850323001022,360470052022001,1,0,1,0,0,1,0,1,0,0,20150727,085,047
5450709,360850323001022,360470890005001,1,0,0,1,0,0,1,1,0,0,20150727,085,047
5450711,360850323001022,360610245005001,1,0,1,0,0,1,0,1,0,0,20150727,085,061
5450712,360850323001022,360850064001009,1,0,0,1,0,1,0,1,0,0,20150727,085,085
5450713,360850323001022,360850074001004,1,0,1,0,0,1,0,1,0,0,20150727,085,085
5450714,360850323001022,360850141002000,1,0,0,1,0,0,1,1,0,0,20150727,085,085
5450715,360850323001022,360850146052004,1,0,1,0,1,0,0,1,0,0,20150727,085,085
5450716,360850323001022,360850177006001,1,0,0,1,0,0,1,1,0,0,20150727,085,085
5450717,360850323001022,360850181003012,1,0,0,1,0,1,0,1,0,0,20150727,085,085
5450718,360850323001022,360850208042010,1,0,0,1,0,0,1,1,0,0,20150727,085,085
5450719,360850323001022,360850277021004,1,0,1,0,0,1,0,1,0,0,20150727,085,085
5450720,360850323001022,360850277053002,1,0,1,0,0,0,1,1,0,0,20150727,085,085
5450721,360850323001022,360850323001010,1,0,0,1,0,1,0,1,0,0,20150727,085,085

In [25]:
nyc_lodes.to_csv('lodes_nyc.csv')

In [30]:
blocks = np.unique(np.concatenate((nyc_lodes['w_geocode'], nyc_lodes['h_geocode'])))

In [35]:
blocks_df = pd.DataFrame({'block': blocks})
blocks_df.to_csv('nyc_blocks_in_lodes.csv')

In [31]:
len(blocks)

32956

In [33]:
nyc_lodes[nyc_lodes['S000']>10]

,w_geocode,h_geocode,S000,SA01,SA02,SA03,SE01,SE02,SE03,SI01,SI02,SI03,createdate,w_county,h_county
220148,360050061001000,360050061002001,14,8,5,1,11,2,1,0,0,14,20150727,005,005
263942,360050149003002,360050227031001,16,2,10,4,0,1,15,0,0,16,20150727,005,005
263943,360050149003002,360050227031002,13,3,9,1,0,0,13,0,0,13,20150727,005,005
291290,360050229013001,360050227031001,18,3,10,5,0,1,17,0,0,18,20150727,005,005
291292,360050229013001,360050227031003,11,1,3,7,0,0,11,0,0,11,20150727,005,005
307211,360050263005000,360050409002000,15,0,10,5,0,7,8,0,0,15,20150727,005,005
321287,360050286001000,360050254001003,11,1,7,3,0,3,8,0,0,11,20150727,005,005
321308,360050286001000,360050261001000,11,3,8,0,0,2,9,0,0,11,20150727,005,005
321454,360050286001000,360050288003000,12,2,6,4,1,1,10,0,0,12,20150727,005,005
321486,360050286001000,360050296001011,117,36,70,11,3,73,41,0,0,117,20150727,005,005
321488,360050286001000,360050296001019,36,17,16,3,2,23,11,0,0,36,20150727,005,005
321489,360050286001000,360050296001020,11,4,5,2,0,7,4,0,0,11,20150727,005,005
321491,360050286001000,360050296002000,132,61,56,15,9,84,39,0,0,132,20150727,005,005
321533,360050286001000,360050307012000,13,2,6,5,2,1,10,0,0,13,20150727,005,005
321970,360050286001000,360050421001002,28,9,13,6,1,3,24,0,0,28,20150727,005,005
321971,360050286001000,360050421002000,12,2,6,4,2,0,10,0,0,12,20150727,005,005
321974,360050286001000,360050421004000,15,5,8,2,1,1,13,0,0,15,20150727,005,005
322125,360050286001000,360050462012001,12,2,7,3,0,3,9,0,0,12,20150727,005,005
322127,360050286001000,360050462013002,13,0,11,2,0,4,9,0,0,13,20150727,005,005
322875,360050286001000,360610044001000,12,4,5,3,5,1,6,0,0,12,20150727,005,061
322969,360050286001000,360610136004001,11,2,8,1,3,1,7,0,0,11,20150727,005,061
323005,360050286001000,360610157002001,12,2,4,6,2,1,9,0,0,12,20150727,005,061
323020,360050286001000,360610165002000,12,0,8,4,3,2,7,0,0,12,20150727,005,061
323085,360050286001000,360610211007000,11,2,6,3,1,2,8,0,0,11,20150727,005,061
323136,360050286001000,360610238011016,12,4,6,2,1,0,11,0,0,12,20150727,005,061
323191,360050286001000,360610267001002,13,5,6,2,1,4,8,0,0,13,20150727,005,061
323231,360050286001000,360610281002001,11,3,6,2,3,1,7,0,0,11,20150727,005,061
337030,360050323004000,360050307012000,13,4,8,1,2,5,6,0,0,13,20150727,005,005
337044,360050323004000,360050323002000,17,4,5,8,9,3,5,0,0,17,20150727,005,005
340366,360050332024000,360050332024000,11,1,6,4,0,5,6,0,0,11,20150727,005,005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5227061,360810849002001,360610016002001,16,0,8,8,4,12,0,0,0,16,20150727,081,061
5227537,360810849002001,360810849001001,15,2,8,5,8,6,1,0,0,15,20150727,081,081
5227538,360810849002001,360810849002000,14,5,7,2,6,7,1,0,0,14,20150727,081,081
5227540,360810849002001,360810849003000,15,1,11,3,10,4,1,0,0,15,20150727,081,081
5234492,360810864001000,360471034001004,12,2,9,1,0,12,0,0,0,12,20150727,081,047
5276403,360810998022000,360810998012001,13,0,10,3,0,10,3,0,0,13,20150727,081,081
5276469,360810998022000,360811010013010,11,1,8,2,4,4,3,0,0,11,20150727,081,081
5303449,360811267001000,360811267001000,12,4,4,4,6,3,3,0,0,12,20150727,081,081
5331001,360811551023000,360811551023000,14,0,10,4,3,4,7,0,0,14,20150727,081,081
5385411,360850027001006,360850040002000,14,5,8,1,2,11,1,0,0,14,20150727,085,085
5385416,360850027001006,360850040003002,13,1,9,3,0,12,1,0,0,13,20150727,085,085
5389824,360850067001011,360850039002003,11,1,7,3,0,3,8,0,0,11,20150727,085,085
5392377,360850070001005,360850007001002,11,3,5,3,1,5,5,0,0,11,20150727,085,085
5392536,360850070001005,360850039002003,17,2,12,3,1,4,12,0,0,17,20150727,085,085
5392550,360850070001005,360850040002000,16,2,9,5,2,8,6,0,0,16,20150727,085,085
5392559,360850070001005,360850040003000,12,3,8,1,1,8,3,0,0,12,20150727,085,085
5392561,360850070001005,360850040003002,13,5,6,2,2,9,2,0,0,13,20150727,085,085
5392587,360850070001005,360850047001001,11,3,4,4,1,5,5,0,0,11,20150727,085,085
5392622,360850070001005,360850059001001,12,1,9,2,0,3,9,0,0,12,20150727,085,085
5392648,360850070001005,360850064003007,26,5,15,6,8,9,9,0,0,26,20150727,085,085
5392933,360850070001005,360850112012029,12,5,5,2,0,5,7,0,0,12,20150727,085,085
5392991,360850070001005,360850114012004,16,0,11,5,0,10,6,0,0,16,20150727,085,085
5393014,360850070001005,360850114022004,11,2,6,3,1,2,8,0,0,11,20150727,085,085
5393159,360850070001005,360850128063000,30,3,21,6,1,15,14,0,0,30,20150727,085,085
5393470,360850070001005,360850146062002,11,2,7,2,0,7,4,0,0,11,20150727,085,085
5393478,360850070001005,360850146063001,11,1,8,2,0,4,7,0,0,11,20150727,085,085
5393761,360850070001005,360850170071000,12,2,8,2,1,1,10,0,0,12,20150727,085,085
5393856,360850070001005,360850170103000,13,2,8,3,0,8,5,0,0,13,20150727,085,085
5393936,360850070001005,360850173002000,18,0,13,5,1,10,7,0,0,18,20150727,085,085
5394652,360850070001005,360850277021004,14,1,11,2,2,3,9,0,0,14,20150727,085,085